version: "3.0"
services:
    jenkins:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: jenkins_ci
        ports:
            - 3030:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins_home:/var/jenkins_home
            - /home:/home
            - ./assets:/assets
              
volumes:
    jenkins_home:
        external: true
